#pragma once

#include <spoopy.h>

#ifndef SPOOPY_ENGINE_VERSION
#define SPOOPY_ENGINE_VERSION VK_MAKE_VERSION(0, 0, 1)
#endif

#ifndef VK_API_VERSION_1_1
#define VK_API_VERSION_1_1 VK_MAKE_VERSION(1, 1, 0)
#endif

#define SPOOPY_DEBUG_MESSENGER VK_HEADER_VERSION >= 121